complete -c linux-doctor -f

# Flags
complete -c linux-doctor -l check -r -d 'Run specific check(s), comma-separated'
complete -c linux-doctor -l list -d 'List available checks'
complete -c linux-doctor -l json -d 'Print findings as JSON'
complete -c linux-doctor -l plain -d 'Print plain tab-separated text'
complete -c linux-doctor -l web -d 'Open visual dashboard in browser'
complete -c linux-doctor -l ai -d 'Add AI summary (needs LLM_API_KEY)'
complete -c linux-doctor -l ai-local -d 'Use a local Ollama model, fully private'
complete -c linux-doctor -l push -r -d 'Post report to fleet server'
complete -c linux-doctor -l html -r -d 'Save a standalone HTML report'
complete -c linux-doctor -l md -r -d 'Save a share-ready Markdown report (redacted)'
complete -c linux-doctor -l compare -r -d 'Diff against a previous JSON report'
complete -c linux-doctor -l severity -r -xa '(high medium info)' -d 'Only findings at this severity'
complete -c linux-doctor -l ignore -r -d 'Hide findings by title'
complete -c linux-doctor -l ignore-code -r -d 'Hide findings by stable code'
complete -c linux-doctor -l ignore-add -r -d 'Persistently ignore a code or title fragment'
complete -c linux-doctor -l ignore-remove -r -d 'Remove a previously ignored code or title fragment'
complete -c linux-doctor -l ignore-list -d 'Show configured ignore patterns'
complete -c linux-doctor -l summary -d 'One-line score + severity counts'
complete -c linux-doctor -l todo -d 'Numbered fix list, ordered by severity'
complete -c linux-doctor -l fix -d 'Dry run: show safe-fix commands for the findings'
complete -c linux-doctor -l yes -d 'With --fix: execute the [apply] safe-fix commands'
complete -c linux-doctor -l interactive -d 'Browse findings in an interactive terminal UI'
complete -c linux-doctor -l notify -d 'Desktop notification when new issues appear'
complete -c linux-doctor -l self-test -d 'Explain the environment'
complete -c linux-doctor -l init -d 'Guided first-run setup'
complete -c linux-doctor -l init-config -d 'Create a starter config file'
complete -c linux-doctor -l check-list -d 'List checks as JSON'
complete -c linux-doctor -l history-json -d 'Print run history as JSON'
complete -c linux-doctor -l history-clear -d 'Clear stored run history'
complete -c linux-doctor -l thresholds-json -d 'Print thresholds as JSON'
complete -c linux-doctor -l thresholds-set -r -d 'Merge thresholds from a JSON payload'
complete -c linux-doctor -l schema -d 'Print the JSON Schema'
complete -c linux-doctor -l profile -d 'Show check durations'
complete -c linux-doctor -l license -d 'Show Pro add-on status'
complete -c linux-doctor -l alert -r -d 'POST an alert webhook'
complete -c linux-doctor -l heartbeat -r -d "Ping a dead-man's switch after every run"
complete -c linux-doctor -l daemon -d 'Run continuously as a scheduled agent'
complete -c linux-doctor -l interval -r -d 'Seconds between --daemon runs'
complete -c linux-doctor -l support -d 'Write a privacy-safe support bundle (JSON)'
complete -c linux-doctor -l no-history -d 'Do not read or write run history'
complete -c linux-doctor -l install-timer -d 'Install the user systemd timer (daily + --notify)'
complete -c linux-doctor -l uninstall-timer -d 'Remove the user systemd timer'
complete -c linux-doctor -l help -s h -d 'Show help'
complete -c linux-doctor -l version -d 'Show version'

# Dynamic check IDs for --check
complete -c linux-doctor -l check -xa '(linux-doctor --list 2>/dev/null | string match -r "^\s+([a-z][a-z0-9-]+)" | string trim)'